services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    runtime: python
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/Keerthana-Hub-Tech/expense-tracker
    autoDeploy: true
